(function(n){function k(e,d,c,g){if("string"!=typeof e)throw"System.register provided no module name";d="boolean"==typeof c?{declarative:!1,deps:d,execute:g,executingRequire:c}:{declarative:!0,deps:d,declare:c};d.name=e;e in m||(m[e]=d);e=d.deps;c=[];g=0;for(var a=e.length;g<a;g++)-1==q.call(c,e[g])&&c.push(e[g]);d.deps=c;d.normalizedDeps=d.deps}function f(e,d){d[e.groupIndex]=d[e.groupIndex]||[];if(-1==q.call(d[e.groupIndex],e)){d[e.groupIndex].push(e);for(var c=0,g=e.normalizedDeps.length;c<g;c++){var a=
m[e.normalizedDeps[c]];if(a&&!a.evaluated){var h=e.groupIndex+(a.declarative!=e.declarative);if(void 0===a.groupIndex||a.groupIndex<h){if(void 0!==a.groupIndex&&(d[a.groupIndex].splice(q.call(d[a.groupIndex],a),1),0==d[a.groupIndex].length))throw new TypeError("Mixed dependency cycle detected");a.groupIndex=h}f(a,d)}}}}function b(e){return w[e]||(w[e]={name:e,dependencies:[],exports:{},importers:[]})}function l(e){if(!e.module){var d=e.module=b(e.name),c=e.module.exports,a=e.declare.call(n,function(a,
e){d.locked=!0;c[a]=e;for(var g=0,h=d.importers.length;g<h;g++){var b=d.importers[g];if(!b.locked){var f=q.call(b.dependencies,d);b.setters[f](c)}}d.locked=!1;return e});d.setters=a.setters;d.execute=a.execute;if(!d.setters||!d.execute)throw new TypeError("Invalid System.register form for "+e.name);for(var a=0,f=e.normalizedDeps.length;a<f;a++){var h=e.normalizedDeps[a],p=m[h],r=w[h];r?h=r.exports:p&&!p.declarative?h=p.module.exports&&p.module.exports.__esModule?p.module.exports:{"default":p.module.exports,
__useDefault:!0}:p?(l(p),r=p.module,h=r.exports):h=g(h);r&&r.importers?(r.importers.push(d),d.dependencies.push(r)):d.dependencies.push(null);if(d.setters[a])d.setters[a](h)}}}function c(e){if(!e.module){var d={},b=e.module={exports:d,id:e.name};if(!e.executingRequire)for(var f=0,l=e.normalizedDeps.length;f<l;f++){var h=m[e.normalizedDeps[f]];h&&c(h)}e.evaluated=!0;if(d=e.execute.call(n,function(d){for(var h=0,b=e.deps.length;h<b;h++)if(e.deps[h]==d){d=e.normalizedDeps[h];h=void 0;if(b=m[d])b.declarative?
a(d,[]):b.evaluated||c(b),h=b.module.exports;else if(h=g(d),!h)throw Error("Unable to load dependency "+d+".");d=(!b||b.declarative)&&h&&h.__useDefault?h["default"]:h;return d}throw new TypeError("Module "+d+" not declared as a dependency.");},d,b))b.exports=d}}function a(e,d){var c=m[e];if(c&&!c.evaluated&&c.declarative){d.push(e);for(var b=0,f=c.normalizedDeps.length;b<f;b++){var h=c.normalizedDeps[b];-1==q.call(d,h)&&(m[h]?a(h,d):g(h))}c.evaluated||(c.evaluated=!0,c.module.execute.call(n))}}function g(e){if(v[e])return v[e];
var d=m[e];if(!d)throw"Module "+e+" not present.";var g=m[e];g.groupIndex=0;var b=[];f(g,b);for(var g=!!g.declarative==b.length%2,q=b.length-1;0<=q;q--){for(var h=b[q],p=0;p<h.length;p++){var k=h[p];g?l(k):c(k)}g=!g}a(e,[]);m[e]=void 0;b=d.module.exports;if(!b||!d.declarative&&!0!==b.__esModule)b={"default":b,__useDefault:!0};return v[e]=b}var m={},q=Array.prototype.indexOf||function(c){for(var d=0,a=this.length;d<a;d++)if(this[d]===c)return d;return-1},w={},v={};return function(c,d){var a;a={register:k,
get:g,set:function(a,c){v[a]=c},newModule:function(a){return a},global:n};a.set("@empty",{});d(a);for(a=0;a<c.length;a++)g(c[a])}})("undefined"!=typeof window?window:global)(["cam-frame"],function(n){n.register("platform",[],function(k){var f;return{setters:[],execute:function(){f=window.navigator.userAgent.includes("Macintosh");k("default",{IS_MAC:f,isExtension:!(!chrome.runtime||!chrome.runtime.id),isTopFrame:window.top===window})}}});n.register("w69b/async-response",[],function(k){k("createSender",
function(f){var b={},l=0,c={};b.sendWithResponse=function(a,b){return new Promise(function(m,q){var k=++l;c[k]=[m,q];f({type:a,data:b,msgId:k})})};b.send=function(a,c){f({type:a,data:c})};b.handleResult=function(a){if(a&&"result"===a.type){var b=c[a.msgId];delete c[a.msgId];if(a.hasOwnProperty("error")||a.isError)b[1](a.error);else b[0](a.data);return!0}return!1};return b});k("createRespond",function(f){return function(b,l){Promise.resolve(b).then(function(c){f({type:"result",msgId:l.msgId,data:c})},
function(c){f({type:"result",msgId:l.msgId,error:c,isError:!0})})}});return{setters:[],execute:function(){}}});n.register("w69b/q",[],function(k){var f;return{setters:[],execute:function(){f={defer:function(){var b={};b.promise=new Promise(function(f,c){b.resolve=f;b.reject=c});return b}};f.when=Promise.resolve.bind(Promise);f.all=Promise.all.bind(Promise);f.reject=Promise.reject.bind(Promise);Promise.prototype.finally||(Promise.prototype.finally=function(b){var f=this.constructor;return this.then(function(c){return f.resolve(b()).then(function(){return c})},
function(c){return f.resolve(b()).then(function(){throw c;})})});k("default",f)}}});n.register("chrome-messaging",[],function(k){function f(b){return b instanceof Error?Promise.reject(b.toString()):Promise.reject(b)}k("sendMessage",function(b,f){return new Promise(function(c,a){chrome.runtime.sendMessage({type:b,data:f},function(b){chrome.runtime.lastError?a(chrome.runtime.lastError):b?"result"===b.type?c(b.data):"error"===b.type&&a(b.data):a()})})});k("respond",function(b,l){Promise.resolve(l).catch(f).then(function(c){b({type:"result",
data:c})},function(c){b({type:"error",data:c})})});return{setters:[],execute:function(){}}});n.register("w69b/promise-tool",["w69b/q"],function(k){var f,b;return{setters:[function(b){f=b.default}],execute:function(){b={wrapChromeError:function(b,c){return function(){var a=Array.prototype.slice.call(arguments,0),g=f.defer();a.push(function(a){chrome.runtime.lastError?g.reject(chrome.runtime.lastError):g.resolve(a)});b.apply(c,a);return g.promise}},wrapCallbacks:function(b,c){return function(){var a=
Array.prototype.slice.call(arguments,0),g=f.defer();a.push(g.resolve.bind(g));a.push(g.reject.bind(g));b.apply(c,a);return g.promise}}};k("default",b)}}});n.register("w69b/webrtc",["w69b/promise-tool","w69b/q"],function(k){function f(a){return a.some(function(a){return!!a.label})}var b,l,c,a;return{setters:[function(a){b=a.default},function(a){l=a.default}],execute:function(){c={};a=window.navigator;c.getUserMedia=a.mediaDevices&&a.mediaDevices.getUserMedia?a.mediaDevices.getUserMedia.bind(a.mediaDevices):
b.wrapCallbacks(a.getUserMedia||a.webkitGetUserMedia||a.mozGetUserMedia||a.msGetUserMedia,a);c.getSources=a.mediaDevices&&a.mediaDevices.enumerateDevices?function(){return l.when(a.mediaDevices.enumerateDevices()).then(function(a){return a.filter(function(a){return a.kind.endsWith("input")}).map(function(a){var b={id:a.deviceId,label:a.label};b.kind=a.kind.substring(0,a.kind.length-5);return b})})}:window.MediaStreamTrack&&MediaStreamTrack.getSources?b.wrapCallbacks(MediaStreamTrack.getSources,MediaStreamTrack):
function(){return Promise.resolve([])};c.getSourcesByKind=function(a){return c.getSources().then(function(b){return b.filter(function(b){return b.kind===a})})};c.getVideoSources=function(){return c.getSourcesByKind("video")};c.getAudioSources=function(){return c.getSourcesByKind("audio")};c.hasCamera=function(){return c.getVideoSources().then(function(a){return 0<a.length})};c.hasMicrophone=function(){return c.getAudioSources().then(function(a){return 0<a.length})};c.hasVideoAccess=function(){return c.getVideoSources().then(f)};
c.hasAudioAccess=function(){return c.getAudioSources().then(f)};k("default",c)}}});n.register("cam-frame",["platform","w69b/async-response","w69b/webrtc","chrome-messaging"],function(k){function f(){function f(){d.pause();t.getTracks().forEach(function(a){a.stop()});t=null}function k(b,c,d){return b&&b.type===m&&(b=b.data)&&u.hasOwnProperty(b.type)?(a.respond(d,u[b.type](b.data)),!0):!1}function n(a){return a instanceof Error?Promise.reject(a.toString()):Promise.reject(a)}function e(a){a=a.data;if(u.hasOwnProperty(a.type)){var b=
Promise.resolve(u[a.type](a.data)).catch(n);x(b,a)}}var d,t,u={start:function(a){t&&f();return c.getUserMedia({video:a}).then(function(a){t=a;a=new Promise(function(a){d||(d=document.createElement("video"),d.volume=0,document.body.appendChild(d));d.addEventListener("canplay",function y(){d.removeEventListener("canplay",y);a({width:d.videoWidth,height:d.videoHeight})})});d.srcObject=t;d.play();return a})},stop:function(){f()},getVideoDevices:function(){return c.getVideoSources()}},x=l.createRespond(function(a){window.parent.postMessage(a,
window.location.origin)});b.isExtension?chrome.runtime.onMessage.addListener(k):(console.debug("camFrame: using dev-only messaging"),window.addEventListener("message",e));window.parent.postMessage(g,"*")}var b,l,c,a,g,m;return{setters:[function(a){b=a.default},function(a){l=a},function(a){c=a.default},function(b){a=b}],execute:function(){g="castifyDrawCamFrameReady";m="camFrameMsgWithResult";f()}}})});
