[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']
hook_add = '''
let g:user_emmet_leader_key='<c-f>'
'''

[[plugins]]
repo = 'deoplete-plugins/deoplete-zsh'
on_ft = ['sh']
